name: catty

services:
  db:
    image: mariadb:11
    restart: unless-stopped

    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

    volumes:
      - catty-db-data:/var/lib/mysql

  app:
    image: ${IMAGE_NAME:-ghcr.io/dmitri919/catty-reminders-app}:${IMAGE_TAG:-lab4}

    restart: unless-stopped

    depends_on:
      - db

    ports:
      - "8181:8181"

    volumes:
      - ./config.json:/app/config.json:ro

volumes:
  catty-db-data:
