events {}

http {
    upstream catty_app {
        server app:8181;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://catty_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
