name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Image Name (lowercase)
        id: prep
        run: |
          echo "repo_lower=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Remote Docker Compose Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: course.prafdin.ru
          username: dmitri
          port: 3173
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            export DEPLOY_REF=${{ github.sha }}
            export IMAGE=ghcr.io/${{ github.repository_owner }}/catty-reminders-app:lab4
            export APP_CONTAINER_NAME=catty-app
            export DB_CONTAINER_NAME=catty-db
            export MARIADB_ROOT_PASSWORD=mypass
            export MARIADB_USER=root
            export MARIADB_PASSWORD=mypass
            export MARIADB_DATABASE=catty_reminders
            export HOST_APP_PORT=8181
            export CONTAINER_APP_PORT=8181
            export HOST_DB_PORT=3306
            export CONTAINER_DB_PORT=3306

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            cd /home/dmitri/app
            docker compose up -d --pull always --remove-orphans

            docker image prune -f

            echo "✅ Deploy complete: $IMAGE"
